/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppWhatIfRouteImport } from './routes/app.what-if'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatIfRoute = AppWhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/health': typeof AppHealthRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/what-if': typeof AppWhatIfRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/health': typeof AppHealthRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/what-if': typeof AppWhatIfRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/health': typeof AppHealthRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/upload': typeof AppUploadRoute
  '/app/what-if': typeof AppWhatIfRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/calendar'
    | '/app/health'
    | '/app/insights'
    | '/app/risk'
    | '/app/transactions'
    | '/app/upload'
    | '/app/what-if'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/calendar'
    | '/app/health'
    | '/app/insights'
    | '/app/risk'
    | '/app/transactions'
    | '/app/upload'
    | '/app/what-if'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/calendar'
    | '/app/health'
    | '/app/insights'
    | '/app/risk'
    | '/app/transactions'
    | '/app/upload'
    | '/app/what-if'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/what-if': {
      id: '/app/what-if'
      path: '/what-if'
      fullPath: '/app/what-if'
      preLoaderRoute: typeof AppWhatIfRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppHealthRoute: typeof AppHealthRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppWhatIfRoute: typeof AppWhatIfRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppHealthRoute: AppHealthRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppRiskRoute: AppRiskRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppUploadRoute: AppUploadRoute,
  AppWhatIfRoute: AppWhatIfRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
